name: Commit-based Code Scanner

on:
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Get path at commit
        id: commit-path
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_PATH=$(git rev-parse --show-toplevel)
          echo "::set-output name=path::$COMMIT_PATH"

      - name: Log current path and commit ID
        run: |
          echo "Current Path: ${{ steps.commit-path.outputs.path }}"
          echo "Commit ID: ${{ github.event.pull_request.head.sha }}"

      - name: Get repository URL
        id: repo-url
        run: |
          echo "::set-output name=url::$(git remote get-url origin)"

      - name: Running Code scanner
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          REPO_URL=${{ steps.repo-url.outputs.url }}
          docker run \
            --rm \
            rohitcoder/hela \
            --code-path $REPO_URL \
            --sast --sca --secret  \
            --verbose \
            --commit-id $COMMIT_ID
